version: '3.3'

services:
  postgres:
    image: postgres:15.1-alpine3.17
    container_name: postgres
    volumes:
      - ./treeftly-psql-data:/var/lib/postgresql/data
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=treeftly
      - POSTGRES_USER=treeftly
    expose:
      - 5432
  treeftly:
    image: mateeyow/treeftly-api:e1901d1
    container_name: treeftly
    ports:
      - 8081:8080
    restart: always
    depends_on:
      - postgres
    environment:
      - AUTH_SECRET=dzNUNWpTeCQlVXZ2eXEqRDJBTA==
      - POSTGRES_DB=postgres://treeftly:treeftly@postgres:5432/treeftly
      - NODE_ENV=production
  # busybox:
  #   image: busybox:latest
  #   depends_on:
  #     - postgres
  #   command: ["/bin/sh", "-c",  "while true; do echo hello; sleep 10;done"]
      
