version: '3.3'

services:
  postgres:
    image: postgres:15.1-alpine3.17
    container_name: postgres
    volumes:
      - ./treeftly-psql-data:/var/lib/postgresql/data
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=${TREEFTLY_USER}
      - POSTGRES_USER=${TREEFTLY_PASSWORD}
    expose:
      - 5432
  treeftly:
    image: mateeyow/treeftly-api:${IMAGE_TAG}
    container_name: treeftly
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres
    environment:
      - AUTH_SECRET=dzNUNWpTeCQlVXZ2eXEqRDJBTA==
      - POSTGRES_DB=postgres://${TREEFTLY_USER}:${TREEFTLY_PASSWORD}@postgres:5432/treeftly
      - NODE_ENV=production
      - NODE_PORT=8080
      - MAIL_HOST=smtp.mailgun.org
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
  # busybox:
  #   image: busybox:latest
  #   depends_on:
  #     - postgres
  #   command: ["/bin/sh", "-c",  "while true; do echo hello; sleep 10;done"]
      
