name: Build and Push Docker Image

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Env Values
        run: |
          git_commit_short=$(git rev-parse --short HEAD)
          echo "GIT_COMMIT_SHORT=$git_commit_short" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: mateeyow
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          # Build's context is the set of files located in the specified PATH or URL
          context: .
          # Push is a shorthand for --output=type=registry
          push: true
          # List of tags
          tags: mateeyow/treeftly-api:${{ env.GIT_COMMIT_SHORT }}