name: Deploy to Cloudboxes

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Execute
        uses: ian-whitestone/action-ssh@master
        with:
          hosts: 'mateeyow@185.107.68.201'
          port: 4881
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          command: |
            ls -al
